### ISSUE TITLE
Membuat Frontend untuk Konfigurasi API Zoom

### ISSUE THREAD

**Issue by mrizkir** [Team-50/Campus50#9]
Sesuai yang telah direncanakan setelah membuat pembagian kelas maka akan dibuatkan zoom meeting secara otomatis. Sebelum ke arah sana perlu dipersiapkan sebuah frontend untuk menyimpan credential integrasi ke zoom yang item-itemnya adalah sebagai berikut (https://marketplace.zoom.us/docs/guides/build/jwt-app) :

- API Key
- API Secret
- IM Chat History Token

Petugas : 
1. @mrizkir menyiapkan struktur table dan backend untuk crud serta testing koneksi
2. @aggry menyiapkan form untuk  menyimpan data2 tersebut
3. @titaniaxu melakukan testing dengan jumlah test case minimal 5.
4. @Fahm93 membuat dokumentasi tentang cara konfigurasi ini untuk end user

Saya sudah menyiapkan api credentialnya silahkan masuk dengan account zoom dosen5; selanjutnya masuk ke url ini : https://marketplace.zoom.us/user/build

**Comment by mrizkir** [comment]
Panduan mas @aggry  supaya bisa olah data zoom api baca file backend/route/api.php bagian :

```php
$router->group(['prefix'=>'h2h','middleware'=>'auth:api'], function () use ($router)
{
    //setting - zoom api
    $router->get('/zoom',['middleware'=>['role:superadmin'],'uses'=>'Plugins\H2H\ZoomAPI\ZoomController@index','as'=>'zoom.index']);
    $router->post('/zoom/store',['middleware'=>['role:superadmin'],'uses'=>'Plugins\H2H\ZoomAPI\ZoomController@store','as'=>'zoom.store']);
    $router->get('/zoom/{id}',['middleware'=>['role:superadmin'],'uses'=>'Plugins\H2H\ZoomAPI\ZoomController@show','as'=>'zoom.show']);
    $router->put('/zoom/{id}',['middleware'=>['role:superadmin'],'uses'=>'Plugins\H2H\ZoomAPI\ZoomController@update','as'=>'zoom.update']);
    $router->delete('/zoom/{id}',['middleware'=>['role:superadmin'],'uses'=>'Plugins\H2H\ZoomAPI\ZoomController@destroy','as'=>'zoom.destroy']);

});
```
Maka endpoint menjadi `/h2h/zoom`

**Comment by mrizkir** [comment]
dokumentasi api zoom https://marketplace.zoom.us/docs/api-reference/introduction

**Comment by mrizkir** [comment]
PR #24 sinkronisasi account dengan zoom. Gimana mas @aggry frontend, udah selesai? kalau ada kendala bisa post disini

**Comment by aggry** [comment]
> PR #24 sinkronisasi account dengan zoom. Gimana mas @aggry frontend, udah selesai? kalau ada kendala bisa post disini

Sedang diproses pak

**Comment by mrizkir** [comment]
code ini dalam file `Zoom.vue` :
`{ text: 'KETERANGAN', value: 'keterangan' },`
diganti menjadi :
`{ text: 'KETERANGAN', value: 'desc' },`

supaya di kolom keterangan muncul nilainya.

**Comment by kevinperdana** [comment]
> code ini dalam file `Zoom.vue` :
> `{ text: 'KETERANGAN', value: 'keterangan' },`
> diganti menjadi :
> `{ text: 'KETERANGAN', value: 'desc' },`
> 
> supaya di kolom keterangan muncul nilainya.

Sudah pak. Cuma blm di push aja sama mas aggry.
